### Site Settings ###
title               : aheil.de 
description         : >-
                      Professor :man_teacher: by day , Nerd and Geek :nerd_face: by night
baseurl             : ""                                # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : aheil/aheil.github.io             # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : aheil/portfolYOU

og_url              : "https://aheil.de"
og_image            : aheil_square.jpg
og_description      : Professor by day, Nerd and Geek by night

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/cv.md


### Author Info ###
author:
  name              : Andreas Heil
  image             : aheil.jpg
#  behance           : your_username
# dribbble          : your_username
  email             : inf@aheil.de
#  facebook          : your_username
  github            : aheil
# gitlab            : your_username
  instagram         : aheil
# kaggle            : your_username
  linkedin          : aheil
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
  twitch            : profaheil
  twitter           : aheil
# vimeo             : your_username
  youtube           : c/AndreasHeil
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  lectures:
    output: true
    permalink: /lectures/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "lectures"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"